### ISSUE TITLE
Password sting shows in Toast when copying even if the password is hidden in the text box

### ISSUE THREAD

**Issue by LineMusha** [NicholaiWP/PasswordGenerator#15]
![image](https://user-images.githubusercontent.com/15612810/235443105-56843419-71a3-49ed-baeb-f5762e8a9e0d.png)
The option to hide the password is in case of someone peeking over your shoulder. But when you then copy the password to your clipboard the Toast shows the password clearly.
Suggestion to change the password string to the word 'password'. Then the full message would then be "successfully copied: password to clipboard"

**Comment by NicholaiWP** [comment]
@LineMusha fixed :)
