### ISSUE TITLE
missing feedback when a new password is generated

### ISSUE THREAD

**Issue by mathiasprisfeldt** [NicholaiWP/PasswordGenerator#3]
Generating a new password is not communicated to the users unless they have the visible password feature turned on.

Consider if it's even necessary to have the hide password functionality turned on by default. Most password generators I know (1Password for instance) show the password when generating.

**Comment by NicholaiWP** [comment]
noted, thanks for the great feedback :D. I'll provide the user with some sort of feedback when a new one is generated and will consider showing the password as default to start with when the app is launched.

**Comment by NicholaiWP** [comment]
@mathiasprisfeldt A visual cue is now given to the user . When users generate a password, the app will display the message: 'A new password has been generated' for 1.5 seconds before disappearing again. The input type of the password field is set to type 'text' as default when the app mounts/on first load.

**Comment by mathiasprisfeldt** [comment]
Looks good, but I'm not that fond of the layout shift it gives. And to be honest I don't think the message is needed since you defaulted it to visible 😄

**Comment by NicholaiWP** [comment]
text will be removed and instead used for the copy-functionality to replace the alert

**Comment by NicholaiWP** [comment]
@mathiasprisfeldt  text now removed when generating a password. Instead, a new component is created that displays a toast when copying a password. It is positioned centered, horizontally at the top of the screen. The toast is dismissable but also dissapears automatically by itself after 3ish seconds. It is live and deployed - check it out :)
