### ISSUE TITLE
Password length input field doesnt restrict user input to only allow 32 characters at maximum

### ISSUE THREAD

**Issue by NicholaiWP** [NicholaiWP/PasswordGenerator#4]
User is able to enter a longer password length than its max value from the form.control element. There needs to be further validation to stop the user from inputting a longer password length than allowed.

**Comment by NicholaiWP** [comment]
Additional validation has been included to validate the user input of the password length input field so that the user can't input integers that exceed the minimum and maximum allowed characters.

**Comment by mathiasprisfeldt** [comment]
This issue can be closed
