### ISSUE TITLE
Download button doesn't work on mobile devices

### ISSUE THREAD

**Issue by NicholaiWP** [NicholaiWP/PasswordGenerator#5]
When clicking the download button on mobile devices, it opens a new page but with no content in it. The new page should include the password that was generated

**Comment by mathiasprisfeldt** [comment]
Consider using native share
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
![image](https://user-images.githubusercontent.com/25567420/234708990-97c2669e-14dd-4800-93a3-b54bbc9e9218.png)

**Comment by NicholaiWP** [comment]
fixed it, but not via navigator though. Do you think i should do a reimplementation to use navigator for such sharing options? @mathiasprisfeldt
