### ISSUE TITLE
Copying the password text while it's hidden doesn't actually copy the password

### ISSUE THREAD

**Issue by mathiasprisfeldt** [NicholaiWP/PasswordGenerator#6]
Since the password is hidden and redacted with "*" it's not the correct text when you copy it manually. Is it intended?

**Comment by NicholaiWP** [comment]
do you mean by highlighting the password consisting of "*" and manually copying it? the text copied from the copy button should be the same whether the input type is text or password otherwise it's a bug

**Comment by mathiasprisfeldt** [comment]
Yes exactly. But of course that's to be expected since the characters are replaced by "*". Also might not be worth it to intercept selecting and copying the text to find the correct corresponding character from the password.

**Comment by NicholaiWP** [comment]
> Yes exactly. But of course that's to be expected since the characters are replaced by "*". Also might not be worth it to intercept selecting and copying the text to find the correct corresponding character from the password.

I think I'll leave it as is. If users wants to copy it, they should use the 'copy' button while input type is 'password' / hidden. But you're absolutely correct. It doesn't copy it correctly - most likely due to the type being changed to password while 'hidden' is active
