### ISSUE TITLE
Window content is scrollable

### ISSUE THREAD

**Issue by mathiasprisfeldt** [NicholaiWP/PasswordGenerator#7]
The content of the window is scrollable even though that it's supposed to be a one pager with floating centered content.
Consider `overflow: hidden;` on body.

**Comment by NicholaiWP** [comment]
Overflow hidden added to body. But i  also added a media query for smaller screens to be able to scroll vertically to see everything

body{
  background: linear-gradient( navy, #203a43) no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
  **overflow: hidden;**
}

**@media only screen and (max-width: 480px){
  body{
      overflow: visible;
  }   
}**
