### ISSUE TITLE
"Ignore special characters" is ignored if any custom special characters are typed in

### ISSUE THREAD

**Issue by mathiasprisfeldt** [NicholaiWP/PasswordGenerator#9]
There should be some visual indication that "Ignore special characters" is disabled if the user has put in their own characters.
Also maybe it would make sense to place that checkbox together with the special characters input field.

**Comment by NicholaiWP** [comment]
moved checkbox together with special character input field

**Comment by NicholaiWP** [comment]
will take care of dis, ty! @mathiasprisfeldt

**Comment by NicholaiWP** [comment]
fixed
